### ISSUE TITLE
Inventory text missing

### ISSUE THREAD

**Issue by amagm6** [rebtd7/FF13Fix#44]
As in the picture below, after applying the fix, it breaks the inventory menu and some other parts with missing text. I have tried previous versions of the fix and they don't seem to do any changes. Not sure what's up. Any help would be appreciated! (Playing on 1440p resolution)

![Screenshot_1](https://user-images.githubusercontent.com/80433847/110718148-573b9480-8202-11eb-9ea4-ff08faaed98e.jpg)

**Comment by Nucleoprotein** [comment]
I noticed that, investigating this issue in #43

**Comment by Nucleoprotein** [comment]
Fixed in e15529e67e9141084f9280d578f3a0a1f1f2bdc3

**Comment by rebtd7** [comment]
Release 1.5.2 includes the commit above, let us know if the issue is fixed

**Comment by amagm6** [comment]
Just checked, everything is fixed, much appreciated for fast deployment of the hotfix! Will close this issue now!

**Comment by Nucleoprotein** [comment]
> Release 1.5.2 includes the commit above, let us know if the issue is fixed

Hmm, why your files are so big? My d3d9.dll is < 200KB now, you use different toolset/compiler? I are using latest VS2019 (16.9.1) with latest Windows SDK and toolset.

**Comment by rebtd7** [comment]
@Nucleoprotein I hadn't updated anything in over an year. After updating I also get < 200KB files.
Btw feel free to create new releases, you don't really need my blessing... just test both games a little so we can try to avoid creating broken releases

**Comment by monochrony** [comment]
This issue is still prevalent at 3840x2160 resolution with version 1.6.4
Inventory and Datalog text entries are not rendering. I haven't changed anything in the config except forcing Vsync.

I'm running a RTX 3080 with Driver version 496.84. Gonna work my way down FFX13Fix versions.

**Comment by Nucleoprotein** [comment]
Hello, I'm back 
I will look at this as I have now 4K display to tests, only need to rebuild my devenv.
Can we upgrade to VS2021 @rebtd7 ?

**Comment by monochrony** [comment]
Nevermind, I found just the issue. I still had a dinput8.dll in the folder. Yes, I'm an idiot. It's working now at 4k without issue. Thank you for replying.

**Comment by rebtd7** [comment]
@monochrony hey, don't be too hard on yourself. glad you got it working

@Nucleoprotein welcome back! sure, feel free to update.

The code is "a bit" messy, I've been meaning to organize/re-write some things but I haven't got too much time to work on this unfortunately.
